services:
  kavita:
    image: jvmilazz0/kavita:0.8.6@sha256:60d1c1c248f2aed9c259d530f486a6bb8a9ab37b74c6b701222c99df3466c2ab
    container_name: kavita
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ${BASE_DATA_DIR}/Mangas:/manga
      - ${BASE_DATA_DIR}/Comics:/comics
      - ${BASE_DATA_DIR}/Books:/books
      - ./config:/kavita/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
