version: "3"
services:
  kavita:
    image: jvmilazz0/kavita:0.8.3@sha256:6d6bf8e9be270637d6741d5204d8a18c4def8fea8cbefe7215c898e470e5ca92
    container_name: kavita
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ${BASE_DATA_DIR}/Mangas:/manga
      - ${BASE_DATA_DIR}/Comics:/comics
      - ${BASE_DATA_DIR}/Books:/books
      - ./config:/kavita/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
