version: "3"
services:
  kavita:
    image: jvmilazz0/kavita:0.8.4@sha256:07393ed7d6860e7312c0197b8c1ebcd4d53c52b7cabd542db08613410ff22c69
    container_name: kavita
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ${BASE_DATA_DIR}/Mangas:/manga
      - ${BASE_DATA_DIR}/Comics:/comics
      - ${BASE_DATA_DIR}/Books:/books
      - ./config:/kavita/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
