services:
  shoko:
    image: ghcr.io/shokoanime/server:v5.3.2@sha256:14acb848d8e67e05a3365c36114df1c6dcdc4ae3aca574f4ee9b163599f1df44
    container_name: shoko
    restart: unless-stopped
    cpus: 4
    mem_limit: 2g
    memswap_limit: 4g
    env_file: .env
    ports:
      - "8111:8111"
    volumes:
      - ./config:/home/shoko/.shoko
      - ${MEDIA_DIR}/anime:/mnt/anime
      - ${DATA_DIR}:/mnt/source
