services:
  shoko:
    image: ghcr.io/shokoanime/server:v5.3.3@sha256:b841f8249c9edfba102e4072e2b2a3eae4179e5dd553f29e11b9898a44f1e836
    container_name: shoko
    restart: unless-stopped
    cpus: 4
    mem_limit: 2g
    memswap_limit: 4g
    env_file: .env
    ports:
      - "8111:8111"
    volumes:
      - ./config:/home/shoko/.shoko
      - ${MEDIA_DIR}/anime:/mnt/anime
      - ${DATA_DIR}:/mnt/source
