services:
  shoko:
    image: ghcr.io/shokoanime/server:v5.3.1@sha256:8bfa235fc36a7147443679c242368f30a532e12de3f52e0de2dcc7743fa37044
    container_name: shoko
    restart: unless-stopped
    cpus: 4
    mem_limit: 2g
    memswap_limit: 4g
    env_file: .env
    ports:
      - "8111:8111"
    volumes:
      - ./config:/home/shoko/.shoko
      - ${MEDIA_DIR}/anime:/mnt/anime
      - ${DATA_DIR}:/mnt/source
