version: "3"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.14.0@sha256:000b7d673d921a03a9168a87c82ba37c5cf3348ba6958fedc794f2b8ea4b0bf9
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - ${DATA_DIR}:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    labels:
      - com.centurylinklabs.watchtower.enable=true
