version: "3"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - ${DATA_DIR}:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    labels:
      - com.centurylinklabs.watchtower.enable=true
