version: "3"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.17.5@sha256:aa88c9f4652872a2a72043511a87d17ec743b60f53e8024e9868ebec5aae59bd
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - ${DATA_DIR}:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    labels:
      - com.centurylinklabs.watchtower.enable=true
