version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:2.6.3@sha256:412551a33f8232bd55e7125a978714816e1b0250f0801f9b1ceb3488cae92c00
    container_name: heimdall
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9000:443"
    volumes:
      - ./config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
