version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:2.7.6@sha256:022f928ecf46d0f773c4a6af80d192a88c77bbc52d78194044589d464532297b
    container_name: heimdall
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9000:443"
    volumes:
      - ./config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
