version: "3"
services:
  heimdall:
    image: linuxserver/heimdall:2.7.6@sha256:d2c76a5e90f4c5a735d74d5279ed0dc9af8e3509d4f977402dc3741251f5529b
    container_name: heimdall
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9000:443"
    volumes:
      - ./config:/config
    labels:
      - com.centurylinklabs.watchtower.enable=true
