version: "3"
services:
  plex-media-healthcheck:
    image: node:24-alpine@sha256:a0b9bf06e4e6193cf7a0f58816cc935ff8c2a908f81e6f1a95432d679c54fbfd
    container_name: plex-media-healthcheck
    env_file: .env
    volumes:
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data:ro
    command: sh -c 'until [[ $(ls -A /data | wc -l) -gt 0 ]]; do echo "Waiting for volume to be ready"; sleep 2; done; echo "Volume ready for use"; sleep infinity;'
    healthcheck:
      test: "[[ $(ls -A /data | wc -l) -gt 0 ]] || exit 1"
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s

  plex:
    image: plexinc/pms-docker:1.43.2.10687-563d026ea@sha256:c37106c57fed7a6624f5dee5a3ce460ff011f09a2aa7f4ee9e8dbbd08ae1b87e
    container_name: plex
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data/media:ro
    depends_on:
      plex-media-healthcheck:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.17.2@sha256:864245fb24830ef6516b5f383bf4d8ba37939ae2f0574dc0217ca02fba4301ff
    container_name: tautulli
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "8181:8181"
    volumes:
      - ./tautulli-config:/config
      - ./config:/plex-config:ro
    depends_on:
      - plex
