version: "3"
services:
  plex-media-healthcheck:
    image: node:24-alpine@sha256:d1b3b4da11eefd5941e7f0b9cf17783fc99d9c6fc34884a665f40a06dbdfc94f
    container_name: plex-media-healthcheck
    env_file: .env
    volumes:
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data:ro
    command: sh -c 'until [[ $(ls -A /data | wc -l) -gt 0 ]]; do echo "Waiting for volume to be ready"; sleep 2; done; echo "Volume ready for use"; sleep infinity;'
    healthcheck:
      test: "[[ $(ls -A /data | wc -l) -gt 0 ]] || exit 1"
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s

  plex:
    image: plexinc/pms-docker:1.43.1.10611-1e34174b1@sha256:8b5bcdf7b506fe051aa1a0a0d464efdb3ad8c0fb1f8a4dfb27a8c489b609920c
    container_name: plex
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data/media:ro
    depends_on:
      plex-media-healthcheck:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.17.0@sha256:9c73937390116e6875970f4c816ddfa9d905cc88f76f2ddbf4eaca2ea2715006
    container_name: tautulli
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "8181:8181"
    volumes:
      - ./tautulli-config:/config
      - ./config:/plex-config:ro
    depends_on:
      - plex
