version: "3"
services:
  plex-media-healthcheck:
    image: node:24-alpine@sha256:01743339035a5c3c11a373cd7c83aeab6ed1457b55da6a69e014a95ac4e4700b
    container_name: plex-media-healthcheck
    env_file: .env
    volumes:
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data:ro
    command: sh -c 'until [[ $(ls -A /data | wc -l) -gt 0 ]]; do echo "Waiting for volume to be ready"; sleep 2; done; echo "Volume ready for use"; sleep infinity;'
    healthcheck:
      test: "[[ $(ls -A /data | wc -l) -gt 0 ]] || exit 1"
      interval: 1m
      timeout: 15s
      retries: 3
      start_period: 15s

  plex:
    image: plexinc/pms-docker:1.43.0.10492-121068a07@sha256:1131c4cd21fa22f8196f749f1dbb69af306776c3c83c7f5b061e51dc49bcff7f
    container_name: plex
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${PLEX_MEDIA_DIR:?media_dir_missing}:/data/media:ro
    depends_on:
      plex-media-healthcheck:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=true

  tautulli:
    image: ghcr.io/tautulli/tautulli:v2.16.1@sha256:5f3603345e3334bd30aadf9e1fa9b0acb401b5225cc42e9b7a3dbf660532fbd9
    container_name: tautulli
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    ports:
      - "8181:8181"
    volumes:
      - ./tautulli-config:/config
      - ./config:/plex-config:ro
    depends_on:
      - plex
