services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.2.2@sha256:cf815209439101842f81d62bb25f7d66140e4cf8c100b4de5d0e84569d38732a
    container_name: wg-easy
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
