# Port 8123 is the default port for Home Assistant
version: "3"
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:fccef878024377273be5d2bb8cc7d63715dd8b255b36543d595eb867549f4a79
    container_name: home-assistant
    restart: unless-stopped
    env_file: .env
    # privileged: true - Required for bluetooth
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
