# Port 8123 is the default port for Home Assistant
version: "3"
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:adb3341e31e03e0048e60d8c1cf952e118a381ae258bb921d3da12a3b27bf0c2
    container_name: home-assistant
    restart: unless-stopped
    env_file: .env
    # privileged: true - Required for bluetooth
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
