# Port 8123 is the default port for Home Assistant
version: "3"
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable@sha256:a6b2a25a4ae7d747506ad3a24bcaf1ee2290fb82811f077447b8847eecd29c56
    container_name: home-assistant
    restart: unless-stopped
    env_file: .env
    # privileged: true - Required for bluetooth
    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro
    network_mode: host
    # labels:
    #   - com.centurylinklabs.watchtower.enable=true
