version: "3"
services:
  portainer-ce:
    image: portainer/portainer-ce:2.31.3@sha256:30e682f04bf1b60d5aa90208ed317e8c61fccd440ceb658323ea64d41d94fcfa
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1001/docker.sock:/var/run/docker-1001.sock
      - portainer_data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  portainer_data:
