version: "3"
services:
  portainer-ce:
    image: portainer/portainer-ce:2.27.3
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/user/1001/docker.sock:/var/run/docker-1001.sock
      - portainer_data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  portainer_data:
