version: "3"
services:
  portainer-ce:
    image: portainer/portainer-ce:2.20.1@sha256:052939c971eb602a56665a6c6e2538dddb3ecdc6f0d0a5f324a4967a74d9c72c
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  portainer_data:
