# Folder structure
# <base-data-dir>
# |-- torrents/
# |   |-- movies/
# |   |-- tv/
# |-- media/
# |   |-- movies/
# |   |-- photos/
# |   |-- tv/

version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:amd64-4.5.5@sha256:d8fdbe40843a9fa6af2754f3f78fbbd15806f9f7f678130dcd1e75d5e6fa691a
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - WEBUI_PORT=9090
    ports:
      - "9090:9090"
    volumes:
      - ./qbit-config:/config
      - ${BASE_DATA_DIR}/torrents:/data/torrents

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.13@sha256:213bb58aa341a0188e64ce2c21e1c5748b167c719828bc61dd904eb0fb1aec63
    container_name: flaresolverr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8191:8191"
    volumes:
      - ./flaresolverr-config:/config

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.12.2.4211@sha256:d6224341a3db5a348f6c204042550065349fff164dba5a4dbe5836e9d3a4a7ae
    container_name: prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-5.2.6.8376@sha256:69504ec278683219a7515b78627c625f00abdedde649f0631f3c200cd9dac933
    container_name: radarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.1.929@sha256:84f6fd558ec25cb74a230040692a8247000d73c3683886c4afeb891a66749c3b
    container_name: sonarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.4.1@sha256:d4f3e4997dfd97bf521358d2282a07d7897f9b8b217d9612db2b4cd5200eaa9a
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${BASE_DATA_DIR}/media:/data/media
    depends_on:
      - qbittorrent
      - prowlarr
