# Folder structure
# <base-data-dir>
# |-- torrents/
# |   |-- movies/
# |   |-- tv/
# |-- media/
# |   |-- movies/
# |   |-- photos/
# |   |-- tv/

version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.4@sha256:dc9e13d2edab18cc7c42367526182b2798f9f0f4c590559337f954fb4e3bdc35
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - WEBUI_PORT=9090
    ports:
      - "9090:9090"
    volumes:
      - ./qbit-config:/config
      - ${BASE_DATA_DIR}/torrents:/data/torrents

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21@sha256:f104ee51e5124d83cf3be9b37480649355d223f7d8f9e453d0d5ef06c6e3b31b
    container_name: flaresolverr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8191:8191"
    volumes:
      - ./flaresolverr-config:/config

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.32.2.4987@sha256:290f3c4b6621bfd7c9e5a99b5a9371cf3d304fbaec5b92026a6c2e62b307e3fa
    container_name: prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-5.21.1.9799@sha256:de9473026ff2f8c89f798660e47c00d24f6d262b1d1aaa71cce02255298d5f4f
    container_name: radarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.14.2939@sha256:6151721d4ce6f34538a7ccf071b0a6f0857470fd1508dff6dcae5ce217a372b2
    container_name: sonarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.1@sha256:ac524ba9783712ef4fe049ed2088d54818435c42dcb0aca2ff1ab8fcd2f89c3d
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${BASE_DATA_DIR}/media:/data/media
    depends_on:
      - qbittorrent
      - prowlarr
