# Folder structure
# <base-data-dir>
# |-- torrents/
# |   |-- movies/
# |   |-- tv/
# |-- media/
# |   |-- movies/
# |   |-- photos/
# |   |-- tv/

version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - WEBUI_PORT=9090
    ports:
      - "9090:9090"
    volumes:
      - ./qbit-config:/config
      - ${BASE_DATA_DIR}/torrents:/data/torrents

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.17@sha256:5f5661db1e69a6f80ac24d47d9fa5580f6f741ee5ec967818396ae0dacecd7ea
    container_name: flaresolverr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8191:8191"
    volumes:
      - ./flaresolverr-config:/config

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.32.2.4987@sha256:41bae5abd4054b91a3ec71d017cbf278bf8b68de67185c40d4e894f5c6d88098
    container_name: prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-5.21.1.9799@sha256:de9473026ff2f8c89f798660e47c00d24f6d262b1d1aaa71cce02255298d5f4f
    container_name: radarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.14.2939@sha256:6151721d4ce6f34538a7ccf071b0a6f0857470fd1508dff6dcae5ce217a372b2
    container_name: sonarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.1@sha256:c26127b0f76e5505bfe275d3301be5d3e47bcc2d59d7d2f50ce5c858bfb01728
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${BASE_DATA_DIR}/media:/data/media
    depends_on:
      - qbittorrent
      - prowlarr
