services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: gluetun
    restart: unless-stopped
    env_file: .env
    ports:
      - "18900:18900" # qbittorrent
      - "18800:9696" # prowlarr
      - "18850:8191" # flaresolverr
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun-config:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: linuxserver/qbittorrent:5.2.3@sha256:352371a7242e8b4aa10958ca02076d1023758070519b89a10251475fb9f1a35a
    container_name: qbittorrent
    network_mode: service:gluetun
    restart: unless-stopped
    env_file: .env
    mem_limit: 500m
    memswap_limit: 1g
    environment:
      - WEBUI_PORT=18900
    volumes:
      - ./qbit-config:/config
      - ${DATA_DIR}:/data/source

  qbit-ui:
    image: ghcr.io/autobrr/qui:v1.23.0@sha256:b1abd18f1d544cd5c63a3b8d9c8a91d097143e04df416567a8cb52040f380ca8
    container_name: qbit-ui
    restart: unless-stopped
    ports:
      - "18950:7476"
    volumes:
      - ./qui-config:/config
    depends_on:
      - qbittorrent

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
    container_name: flaresolverr
    restart: unless-stopped
    env_file: .env
    network_mode: service:gluetun

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.4.0.5397@sha256:48303a36e691a7b65d3016737c1359ec5db484647904d676535f62546708a075
    container_name: prowlarr
    restart: unless-stopped
    env_file: .env
    network_mode: service:gluetun
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-6.2.1.10461@sha256:d61e322a53aef533ae8880a537943a3947116aae304c1df02766585ae2110134
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    ports:
      - "18100:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${DATA_DIR}:/data/source
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.19.2979@sha256:10dcfb916c58ff20e5746b7b7a946763403458067dd5d75d9478c99fd3062607
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    ports:
      - "18000:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${DATA_DIR}:/data/source
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-v1.5.6@sha256:8db8bd2ff0ad23ca111873a5a5be312edf448e74536a5472a0ab02ff36408f76
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "18500:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr
