# Folder structure
# <base-data-dir>
# |-- torrents/
# |   |-- movies/
# |   |-- tv/
# |-- media/
# |   |-- movies/
# |   |-- photos/
# |   |-- tv/

version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:amd64-4.5.5@sha256:d8fdbe40843a9fa6af2754f3f78fbbd15806f9f7f678130dcd1e75d5e6fa691a
    container_name: qbittorrent
    restart: unless-stopped
    env_file: .env
    environment:
      - WEBUI_PORT=9090
    ports:
      - "9090:9090"
    volumes:
      - ./qbit-config:/config
      - ${BASE_DATA_DIR}/torrents:/data/torrents

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.17@sha256:5f5661db1e69a6f80ac24d47d9fa5580f6f741ee5ec967818396ae0dacecd7ea
    container_name: flaresolverr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8191:8191"
    volumes:
      - ./flaresolverr-config:/config

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.24.3.4754@sha256:533b4700d63029ddd219fb07bea32ea2401124c883ade5da9023d168e454751b
    container_name: prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "9696:9696"
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-5.12.2.9335@sha256:5290284a8a1186450b72f08551d7e2cb7f8e7c6bb1491637367a36539b07549c
    container_name: radarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.9.2244@sha256:68e2eae80b938d2bd79f81423ca02c31b34b6b69576a7c6b71ad726213a48189
    container_name: sonarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${BASE_DATA_DIR}:/data
    depends_on:
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.4.5@sha256:df8ecd7047b1f8afaf86b06e0eda87ea87a855356b5923718e6188c3fc2de689
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${BASE_DATA_DIR}/media:/data/media
    depends_on:
      - qbittorrent
      - prowlarr
