services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
    container_name: gluetun
    restart: unless-stopped
    env_file: .env
    ports:
      - "18900:18900" # qbittorrent
      - "18800:9696" # prowlarr
      - "18850:8191" # flaresolverr
    cap_add:
      - NET_ADMIN
    volumes:
      - ./gluetun-config:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun

  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4@sha256:1fc78c81850d658f17701bfa9d8de58ccc12ff27d36a9a176c6299e55aaf4b4e
    container_name: qbittorrent
    network_mode: service:gluetun
    restart: unless-stopped
    env_file: .env
    mem_limit: 500m
    memswap_limit: 1g
    environment:
      - WEBUI_PORT=18900
    volumes:
      - ./qbit-config:/config
      - ${DATA_DIR}:/data/source

  qbit-ui:
    image: ghcr.io/autobrr/qui:v1.16.1@sha256:07b6ea9572e52e8b5f70f8fb15a7c688d8d754a7616242d3ad0b21dbd5c05836
    container_name: qbit-ui
    restart: unless-stopped
    ports:
      - "18950:7476"
    volumes:
      - ./qui-config:/config
    depends_on:
      - qbittorrent

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
    container_name: flaresolverr
    restart: unless-stopped
    env_file: .env
    network_mode: service:gluetun

  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.3.5.5327@sha256:610e8b19a16b355b03ce154b2dfe5d5049725e5ee8f079e421234a39599f11d2
    container_name: prowlarr
    restart: unless-stopped
    env_file: .env
    network_mode: service:gluetun
    volumes:
      - ./prowlarr-config:/config
    depends_on:
      - flaresolverr

  radarr:
    image: ghcr.io/hotio/radarr:release-6.1.1.10360@sha256:a0378fd5be0d23e23eea5f183e12619d2c1d74f70e5dc4a124c315343595f2ae
    container_name: radarr
    restart: unless-stopped
    env_file: .env
    ports:
      - "18100:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./radarr-config:/config
      - ${DATA_DIR}:/data/source
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr

  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.17.2952@sha256:67e97fff243bcbac298c7fbfeae7cbda50790846ec7e1b493ae2d02867128010
    container_name: sonarr
    restart: unless-stopped
    env_file: .env
    ports:
      - "18000:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./sonarr-config:/config
      - ${DATA_DIR}:/data/source
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr

  bazarr:
    image: ghcr.io/hotio/bazarr:release-v1.5.6@sha256:4b1c07f912028f273ed7a9977762f56f4a80dd0876a66a367fd8ad4c1544a33a
    container_name: bazarr
    restart: unless-stopped
    logging:
      driver: json-file
    env_file: .env
    ports:
      - "18500:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bazarr-config:/config
      - ${MEDIA_DIR}:/data/media
    depends_on:
      - gluetun
      - qbittorrent
      - prowlarr
