version: "3"
services:
  web_recipes:
    image: vabene1111/recipes:2.6.1@sha256:22a93021d14c1f4b0f7a3eebac22f3cddba4328b7a43861630881a4008d09d8d
    container_name: tandoor
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "7000:80"
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./db.sqlite3:/opt/recipes/db.sqlite3
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  staticfiles:
