version: "3"
services:
  web_recipes:
    image: vabene1111/recipes:2.6.9@sha256:969c5b3552ffbf18a6f82b3ad5babbae89bfbd30ab6e3195fd3c158bcf3062ed
    container_name: tandoor
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "7000:80"
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./db.sqlite3:/opt/recipes/db.sqlite3
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  staticfiles:
